[profile.default]
src = 'contracts'
ffi = true
build_info = true
extra_output = ['storageLayout', 'evm.gasEstimates']
fs_permissions = [{ access = "read", path = "/"}]
allow_paths = ["../.."]

remappings=[
  '@sphinx-labs/plugins=../../node_modules/@sphinx-labs/plugins/contracts/foundry',
  '@sphinx-labs/contracts=node_modules/@sphinx-labs/contracts/',
  'forge-std/=node_modules/forge-std/src/',
  'ds-test/=node_modules/ds-test/src/'
]

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
