[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
ffi = true
build_info = true
extra_output = ['storageLayout']
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
