[profile.default]
script = 'script'
test = 'test'
ffi = true
build_info = true
extra_output = ['storageLayout']
fs_permissions = [{ access = "read-write", path = "./"}]
allow_paths = ["../.."]
# We highly recommend setting the optimizer to 'false' for development because
# this makes compilation happen ~5x faster. See here for more details:
# https://book.getfoundry.sh/reference/forge/forge-build?highlight=optimizer#conditional-optimizer-usage
optimizer = false

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
