[profile.default]
src = 'contracts'
fs_permissions = [{ access = "read", path = "./"}]
verbosity = 2
ffi = true
solc = '0.8.4'
optimizer = false
test = 'test'
script = 'scripts'
build_info = true
remappings = [
  '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
  '@eth-optimism/contracts/=node_modules/@eth-optimism/contracts',
  'sphinx-forge-std/=node_modules/sphinx-forge-std/src/',
  'ds-test/=node_modules/ds-test/src/',
  '@gnosis.pm/safe-contracts-1.3.0/=node_modules/@gnosis.pm/safe-contracts/contracts/',
  '@gnosis.pm/safe-contracts-1.4.1/=node_modules/@gnosis.pm/safe-contracts-1.4.1/contracts/'
]

[profile.core]
src = 'contracts/core'

[profile.lite]
optimizer = false

[fmt]
line_length=100
multiline_func_header="all"
bracket_spacing=true
wrap_comments=true
