name: Publish Docker image

on:
  push:
    branches:
      - develop

jobs:
  checkchanged:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.step1.outputs.didChange }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: step1
        run: >
          echo \
            "didChange=$(./ops/ci-builder/check-changed.sh ops/ci-builder/Dockerfile \
            ${{github.event.before}} ${{github.event.after}} \
            )" >> "$GITHUB_OUTPUT"

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: checkchanged
    if: ${{needs.checkchanged.outputs.changed}}
    name: Push Docker image to Docker Hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: samgoldman
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: samgoldman/ci-builder:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./ops/ci-builder/
          file: ./ops/ci-builder/Dockerfile
          push: true
          tags: samgoldman/ci-builder:latest, samgoldman/ci-builder:${{github.event.after}}
          labels: ${{ steps.meta.outputs.labels }}
